# comentario para testar
version: '3'
services:

  webmail:
    build:
      context: .
      dockerfile: Dockerfile
    image: webmail
    container_name: webmail
    networks:
      - asa-network
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: portal
    container_name: portal
    networks:
      - asa-network
  intranet:
    build:
      context: .
      dockerfile: Dockerfile
    image: intranet
    container_name: intranet
    networks:
      - asa-network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: proxy
    container_name: proxsy
    ports:
      - "8080:80"
    depends_on:
      - webmail
      - portal
      - intranet
    networks:
      - asa-network

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    hostname: ns1.pa.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/etc:/etc/bind
    networks:
      - asa-network


#Docker Networks
networks:
  asa-network:
    driver: bridge

#Volumes
db:
  wordpress: