# comentario para testar
version: '3'
services:

  web01:
    build:
      context: .
      dockerfile: Dockerfile.c01
    image: web01
    container_name: web01
    networks:
      - asa-network
  web02:
    build:
      context: .
      dockerfile: Dockerfile.c02
    image: web02
    container_name: web02
    networks:
      - asa-network
  web03:
    build:
      context: .
      dockerfile: Dockerfile.c03
    image: web03
    container_name: web03
    networks:
      - asa-network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    image: proxy
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - web01
      - web02
      - web03
    networks:
      - asa-network

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile.ds01
    image: dns
    container_name: dns
    hostname: ns1.pa.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/etc:/etc/bind
    networks:
      - asa-network


#Docker Networks
networks:
  asa-network:
    driver: bridge
