# comentario para testar
version: '3'
services:

  webmail:
    build:
      context: ./webmail
      dockerfile: Dockerfile
    image: webmail
    container_name: webmail
    networks:
      - asa-network
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    image: portal
    container_name: portal
    networks:
      - asa-network
  intranet:
    build:
      context: ./intranet
      dockerfile: Dockerfile
    image: intranet
    container_name: intranet
    networks:
      - asa-network
  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    image: email
    container_name: email
    networks:
      - asa-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - webmail
      - portal
      - intranet
    networks:
      - asa-network

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    hostname: ns1.pa.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/etc:/etc/bind
    networks:
      - asa-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
 
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
 


#Docker Networks
networks:
  asa-network:
    driver: bridge